name: Deploy AWS CDK

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk' 

      - name: Install Requirements 
        run: 'pip3 install -r requirements.txt'
        working-directory: .

      - name: CDK Synth
        run: cdk synth
        working-directory: .
              
      - name: CDK Deploy
        run: cdk deploy --require-approval never
        working-directory: .
        
