name: CD - Deploy to ECS via CDK (POC)

on:
  push:
    branches:
      - master   # Deploy on pushes to master
  workflow_dispatch:  # Allow manual trigger from GitHub UI

permissions:
  contents: read    # Checkout code

jobs:
  deploy:
    # If you run in a self-hosted AWS runner, replace with:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./aws_cdk 

      - name: Build CDK App
        run: npm run build

      - name: Deploy ECS with CDK (Rolling Update)
        env:
          CDK_NEW_BOOTSTRAP: 1
        run: |
          npx cdk deploy --all --require-approval=never


