name: CI - CDK DEPLOY (POC)

on:
  push:
    tags:
      - 'v*'
    branches:
      - main    # Trigger only on pushes to master branch
env:
  AWS_REGION: ${{ secrets.REGION }}
  ECR_REPOSITORY:  ${{ secrets.ECR_REPO }}  
  ECR_REPO_NAME:  ${{ secrets.ECR_REPO_NAME }}  
  ROLE_ARN:  ${{ secrets.ROLE_ARN }}  

permissions:
  contents: read   # Required for checkout

jobs:
  deploy:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, linux, X64]   # Your AWS Runner labels

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Node.js (for CDK CLI)
      - name: Install Node.js and npm
        run: |
          sudo apt update -y
          sudo apt install -y nodejs npm
          node -v
          npm -v

      # Install AWS CDK globally
      - name: Install AWS CDK
        run: |
          sudo npm install -g aws-cdk
          cdk --version
      
      # CDK synthesize 
      - name: CDK Synth
        run: |
          cdk synth
        working-directory: ./aws_cdk   

      # CDK Deploy (rolling update for ECS)
      - name: CDK Deploy
        run: |
          cdk deploy --require-approval=never
        working-directory: ./aws_cdk










