name: CD - Deploy to ECS via CDK (POC)

on:
  push:
    branches:
      - master   # Deploy on pushes to master
  workflow_dispatch:  # Allow manual trigger from GitHub UI

permissions:
  contents: read    # Checkout code

jobs:
  deploy:
    # If you run in a self-hosted AWS runner, replace with:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Node.js (for CDK CLI)
      - name: Install Node.js and npm
        run: |
          sudo apt update -y
          sudo apt install -y nodejs npm
          node -v
          npm -v

      # Install AWS CDK globally
      - name: Install AWS CDK
        run: |
          sudo npm install -g aws-cdk
          cdk --version

      - name: Prepare Python Environment
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          .venv/bin/pip install --upgrade pip setuptools wheel
          .venv/bin/pip install -r requirements.txt
        working-directory: ./aws_cdk

      - name: CDK Deploy
        run: |
          . .venv/bin/activate
          cdk deploy --require-approval=never --app ".venv/bin/python app.py"
        working-directory: ./aws_cdk










