name: CD - Deploy ECS Cluster (POC)

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
permissions:
  contents: read 

jobs:
  build-and-deploy:
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Node.js and aws cdk
        run: |
          sudo apt update -y
          sudo apt install -y nodejs npm
          sudo npm install -g aws-cdk
      
      - name: Set up Python and install dependencies
        working-directory: ./ecs_stack
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-venv python3-pip build-essential libssl-dev python3-dev
          python3 -m venv .venv
          .venv/bin/python -m pip install --upgrade pip wheel setuptools
          .venv/bin/pip install -r requirements.txt

      - name: Test CDK App Entry Point
        working-directory: ./ecs_stack
        run: .venv/bin/python app.py

      - name: CDK Synth
        working-directory: ./ecs_stack
        # run: cdk synth --app "python3 app.py"
        run: cdk synth --app ".venv/bin/python app.py"

      - name: CDK Deploy
        working-directory: ./ecs_stack
        run: cdk deploy --require-approval=never --app ".venv/bin/python app.py"
