name: CD - Deploy ECS Cluster (POC)

on:
  workflow_run:
    workflows: ["CI - Build and Push to ECR (POC)"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, linux, X64]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install npm
        run: 'sudo apt update -y && sudo apt install nodejs npm -y'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Install Python & Create Virtual Env
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-venv python3-pip
          python3 -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
        working-directory: .

      - name: CDK Synth
        run: |
          cdk synth
        working-directory: ./ecs_stack

      - name: CDK Deploy
        run: |
          cdk deploy --require-approval=never
        working-directory: ./ecs_stack



